#pragma once
#include <filesystem>
#include <optional>
#include <unordered_map>
#include <functional>
#include <string>
#include <vector>

#include <gp_Trsf.hxx>
#include <TDF_Label.hxx>
#include <TopoDS_Shape.hxx>
#include <Quantity_Color.hxx>
#include <Standard_Handle.hxx>
#include <TDF_Label.hxx>

#pragma push_macro("Handle")
#undef Handle

#include <pxr/usd/sdf/path.h>

#pragma pop_macro("Handle")


class TDocStd_Application;
class TDocStd_Document;
class XCAFDoc_ColorTool;
class XCAFDoc_LayerTool;
class XCAFDoc_MaterialTool;
class XCAFDoc_ShapeTool;

namespace occt = opencascade;
namespace fs = std::filesystem;

PXR_NAMESPACE_USING_DIRECTIVE

// TDF_Label is a handle into the document's label tree. Two labels pointing
// at the same node are equal — we use that for deduplicating definitions.
// We hash by walking the tag chain to the container, which uniquely identifies
// any node in the tree.
struct LabelHash {
    size_t operator()(const TDF_Label& label) const {
        size_t h = 0;
        TDF_Label l = label;
        while (!l.IsNull()) {
            h ^= std::hash<int>{}(l.Tag()) + 0x9e3779b9 + (h << 6) + (h >> 2);
            l = l.Father();
        }
        return h;
    }
};

struct LabelEqual {
    bool operator()(const TDF_Label& a, const TDF_Label& b) const {
        return a.IsEqual(b);
    }
};

template<typename V>
using LabelMap = std::unordered_map<TDF_Label, V, LabelHash, LabelEqual>;

std::string getLabelName(const TDF_Label& label);

static bool isAutoGeneratedName(const std::string& s) {
    return s.empty() || s == "COMPOUND" || s == "SOLID" || 
           s == "SHELL" || s == "COMPSOLID" || (!s.empty() && s[0] == '=');
}

std::string stableLabelSuffix(const TDF_Label& label);

struct CADBundleKey {
    fs::path xbfPath;
    SdfPath primPath;
    
    bool operator==(const CADBundleKey& other) const {
        return xbfPath == other.xbfPath;
    }
    struct Hash {
        size_t operator()(const CADBundleKey& k) const {
            return std::hash<std::string>{}(k.xbfPath.string());
        }
    };
};


struct OpenCascadeAssembly {

    enum class PartNodeType {
        Assembly,
        Leaf
    };

    struct PartNode {
        PartNodeType type;
        TDF_Label definitionLabel; // this is the key into definitionShapes
        TDF_Label instanceLabel;
        TopAbs_ShapeEnum shapeType;
        gp_Trsf localTransform;  // this node's transform relative to its parent only
        int parentIdx;       // index into partNodes[], -1 if container
        int firstChildIdx;   // first child index, children occupy contiguous range in partNodes[]
        int childCount;
        int depth;
        bool visible = true;

        std::string name;
        std::optional<Quantity_Color> color;
    };

    struct ExportablePart {
        SdfPath      path;       // unix-esc path, same as getNodePaths() produces
        TDF_Label    definitionLabel;  // the underlying shape's label
        TopoDS_Shape localShape;    // shape in local/object space, untransformed
        gp_Trsf      worldTransform;   // this instance's accumulated placement
    };

    OpenCascadeAssembly(
        fs::path xbfPath,
        occt::handle<TDocStd_Application> a,
        occt::handle<TDocStd_Document>    d,
        occt::handle<XCAFDoc_ShapeTool>   st,
        occt::handle<XCAFDoc_ColorTool>    ct,
        occt::handle<XCAFDoc_MaterialTool>   mt,
        occt::handle<XCAFDoc_LayerTool>   lt,
        double metersPerUnit
    ) : xbfPath(xbfPath), app(a), doc(d), shapeTool(st), colorTool(ct), materialTool(mt), layerTool(lt), metersPerUnit(metersPerUnit) {}

    static std::optional<OpenCascadeAssembly> loadFromFile(
        const fs::path& xbfPath
    );

    const std::vector<std::pair<TDF_Label, TopoDS_Shape>>& getDefinitionShapes();
    const std::vector<SdfPath> getNodePaths(const SdfPath &assemblyRoot) const;
    const std::vector<ExportablePart> getExportableLeaves(const SdfPath& assemblyRoot) const;

    void buildInstanceTree();

    void debugPrintInstances() const;

    occt::handle<TDocStd_Application> app;
    occt::handle<TDocStd_Document> doc;
    occt::handle<XCAFDoc_ShapeTool> shapeTool;
    occt::handle<XCAFDoc_ColorTool> colorTool;
    occt::handle<XCAFDoc_MaterialTool> materialTool;
    occt::handle<XCAFDoc_LayerTool> layerTool;

    std::vector<PartNode> partNodes;        // flat pre-order tree

    LabelMap<TDF_Label> canonicalLabelMap;
    LabelMap<TopoDS_Shape> definitionShapes; // definition label -> geometry
    LabelMap<std::string> definitionNames;  // definition label -> name
    LabelMap<std::string> definitionLabelSuffixes;  // definition label -> clean name
    LabelMap<SdfPath> protoPaths;
    
    fs::path xbfPath;
    
    double metersPerUnit;
    
private:
    std::vector<std::pair<TDF_Label, TopoDS_Shape>> defs;

    int countNodes(const TDF_Label& label);
    int countAssemblyChildren(const TDF_Label& assemblyDef);
    bool isLabelVisible(const TDF_Label& label) const;
    
    void fillNode(
        const TDF_Label& instLabel,
        const TDF_Label& defLabel,
        const std::string& parentName,
        const gp_Trsf& parentWorld,
        int parentIdx,
        int depth,
        int& cursor
    );
    
    void fillLeaf(
        const TDF_Label& instLabel, 
        const TDF_Label& defLabel,
        const std::string& parentName,
        const gp_Trsf& localTrsf,
        int parentIdx,
        int depth,
        int& cursor
    );
    
    void fillAssembly(
        const TDF_Label& instLabel, 
        const TDF_Label& defLabel,
        const std::string& parentName,
        const gp_Trsf& localTrsf,
        const gp_Trsf& world,
        int parentIdx,
        int depth,
        int& cursor
    );
};