#!/usr/bin/bash 

#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ABS_PLUGIN_PATH="$SCRIPT_DIR/entry"

export ARNOLD_PLUGIN_PATH="$ABS_PLUGIN_PATH:$ARNOLD_PLUGIN_PATH"
#export MULTI_USD_VERSION="25.5"
