#include <ostream>
#include <iostream>
#include <utility>
#include <unordered_map>
#include <unordered_set>
#include <string>
#include <vector>
#include <mutex>
#include <atomic>

#include <opencascade/TDF_Label.hxx>
#include <opencascade/Quantity_Color.hxx>
#include <opencascade/TopoDS_Shape.hxx>
#include <opencascade/gp_XYZ.hxx>
#include <opencascade/TDF_Tool.hxx>

#pragma push_macro("Handle")
#undef Handle

#include <pxr/pxr.h>
#include <pxr/usd/usd/common.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/modelAPI.h>
#include <pxr/usd/usd/inherits.h>
#include <pxr/usd/usd/attribute.h>
#include <pxr/usd/usd/references.h>
#include <pxr/usd/usd/variantSets.h>
#include <pxr/usd/usd/editContext.h>

#include <pxr/usd/sdf/changeBlock.h>
#include <pxr/usd/sdf/types.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/usd/sdf/variantSpec.h>
#include <pxr/usd/sdf/variantSetSpec.h>

#include <pxr/usd/usdGeom/mesh.h>
#include <pxr/usd/usdGeom/xform.h>
#include <pxr/usd/usdGeom/scope.h>
#include <pxr/usd/usdGeom/tokens.h>
#include <pxr/usd/usdGeom/primvarsAPI.h>
#include <pxr/usd/usdGeom/basisCurves.h>
#include <pxr/usd/usdGeom/imageable.h>
#include <pxr/usd/usdGeom/subset.h>
#include <pxr/usd/usdGeom/primvar.h>
#include <pxr/usd/usdGeom/xformOp.h>

#include <pxr/usd/sdf/copyUtils.h>
#include <pxr/base/work/loops.h>

#include <pxr/base/vt/array.h>
#include <pxr/base/vt/types.h>
#include <pxr/base/tf/staticData.h>
#include <pxr/base/tf/token.h>
#include <pxr/base/gf/vec3f.h>

#pragma pop_macro("Handle")

#include "stepAPI.h"

#include "StepUsdPipeline.h"
#include "OpenCascadeAssembly.h"
#include "Logger.h"
#include "UsdUtils.h"

PXR_NAMESPACE_USING_DIRECTIVE

// Write CAD pat
void StepUsdPipeline::writePartClass(
    UsdStageRefPtr prototypesStage,
    const UsdPrim& prototypesPrimOnContainerStage,
    const SdfPath& partPath
) {
    std::optional<SdfReference> defaultParamsRef = StepUsdPipeline::getPrototypesDefaultParams(prototypesPrimOnContainerStage);

    fs::path containerStagePath = fs::canonical(
        prototypesPrimOnContainerStage.GetStage()->GetRootLayer()->GetResolvedPath().GetPathString()
    );
    fs::path prototypesStagePath = fs::canonical(
        prototypesStage->GetRootLayer()->GetResolvedPath().GetPathString()
    );

    fs::path relativePath = fs::relative(containerStagePath, prototypesStagePath.parent_path());

    SdfPath realPartClassPath = this->pathConfig.containerPrimPath.AppendChild(partPath.GetNameToken());
    UsdPrim partPrim = prototypesStage->CreateClassPrim(realPartClassPath);

    prototypesStage->GetPrimAtPath(this->pathConfig.containerPrimPath).SetSpecifier(SdfSpecifierOver);

    UsdGeomImageable(partPrim).CreateVisibilityAttr().Set(UsdGeomTokens->inherited);

    auto makeClassChild = [&](const char* name) {
        SdfPath childPath = realPartClassPath.AppendChild(TfToken(name));
        UsdPrim child = prototypesStage->OverridePrim(childPath);
        UsdGeomImageable(child).CreateVisibilityAttr().Set(UsdGeomTokens->inherited);
    };

    makeClassChild("Mesh");
    makeClassChild("Wireframe");
    makeClassChild("Sketch");
    makeClassChild("SketchPlanes");
    
    if (defaultParamsRef.has_value()) {
        partPrim.GetPrim().GetReferences().AddReference(
            relativePath.string(),
            defaultParamsRef->GetPrimPath(),
            defaultParamsRef->GetLayerOffset()
        );
    }
}

// MARK: - Write Prototype Xforms
void StepUsdPipeline::writePrototypeXformsInPrototypesStage(
    UsdStageRefPtr prototypesStage,
    const std::vector<std::pair<TDF_Label, TopoDS_Shape>>& defs,
    const std::unordered_set<SdfPath, SdfPath::Hash>& selectedPaths,
    const std::string& variantSetName,
    const std::string& variantName,
    const LabelMap<std::string>& definitionNames,
    LabelMap<SdfPath>& prototypePaths,
    bool makeFreshStage
) {
    const int total = (int)defs.size();
    int completed = 0;

    std::string logLabel = "";
    if (!variantSetName.empty()) {
        logLabel = " {" + variantSetName + "=" + variantName + "}";
    }

    std::optional<SdfReference> defaultParamsRef;
    fs::path relativePath;

    UsdGeomXform::Define(prototypesStage, this->pathConfig.containerPrimPath);
    
    SdfPath partPath = this->pathConfig.containerPrimPath.AppendChild(TfToken("Part"));

    for (int defIdx = 0; defIdx < total; defIdx++) {
        const TDF_Label& defLabel = defs[defIdx].first;

        // Guard against already-processed label — use defLabel, not iterator
        if (prototypePaths.count(defLabel)) {
            completed++;
            continue;
        }

        auto it = definitionNames.find(defLabel);
        std::string rawName;
        bool hasRealName = (it != definitionNames.end()
                            && !it->second.empty()
                            && !isAutoGeneratedName(it->second));

        std::string suffix = stableLabelSuffix(defLabel);

        if (hasRealName) {
            rawName = sanitizeUsdName(it->second) + "__" + suffix;
        } else {
            rawName = "__" + suffix;
        }

        SdfPath protoPath = this->pathConfig.prototypesPath.AppendChild(TfToken(rawName));
        prototypePaths[defLabel] = protoPath;

        if (!makeFreshStage && prototypesStage->GetPrimAtPath(protoPath).IsValid()) {
            completed++;
            if (Logger::activeLevel == Logger::DEBUG) {
                //LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Skip existing prototype: " + protoPath.GetString());
            } else {
                LOG_PROGRESS(completed, total, "Writing prototypes " + logLabel);
            }
            continue;
        }

        UsdPrim protoPrim = prototypesStage->DefinePrim(protoPath);

        {
            SdfChangeBlock changeBlock;

            if (!protoPrim.IsValid()) {
                std::cerr << "writePrototypeXform: prim invalid after Define at " << protoPath << "\n";
                continue;
            }

            std::string displayName = hasRealName ? it->second : ("Part_" + suffix);
            protoPrim.SetDisplayName(displayName);
            protoPrim.GetInherits().AddInherit(partPath);

        }

        completed++;
        if (Logger::activeLevel == Logger::DEBUG) {
            LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Writing prototype: " + protoPath.GetString());
        } else {
            LOG_PROGRESS(completed, total, "Writing prototypes " + logLabel);
        }
    }
    LOG_PROGRESS_DONE();
}

void StepUsdPipeline::writePrototypeOverridesInAssemblyStage(
    UsdStageRefPtr assemblyStage,
    LabelMap<SdfPath>& prototypePaths
) {
    LOG_SCOPED_TIMER("writePrototypeOverridesInAssemblyStage");
    const int total = (int)prototypePaths.size();
    int completed = 0;
    
    { // SdfChangeBlock
        SdfChangeBlock changeBlock;

        for (auto protoIter = prototypePaths.begin(); protoIter != prototypePaths.end(); ++protoIter) {
            const SdfPath& protoPath = protoIter->second;
            assemblyStage->OverridePrim(protoPath);

            completed++;
            if (Logger::activeLevel == Logger::DEBUG) {
                LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Writing Assembly Override: " + protoPath.GetString());
            } else {
                LOG_PROGRESS(completed, total, "Writing Prototype Overrides");
            }
        }
        completed = 0;
    }
    { // SdfChangeBlock
        SdfChangeBlock changeBlock;
        for (auto protoIter = prototypePaths.begin(); protoIter != prototypePaths.end(); ++protoIter) {
            const TDF_Label& label = protoIter->first;
            const SdfPath& protoPath = protoIter->second;
            const UsdPrim& protoPrim = assemblyStage->GetPrimAtPath(protoPath);

            TCollection_AsciiString entry;
            TDF_Tool::Entry(label, entry);
            
            AutolibStepAPI api(protoPrim);
            UsdGeomPrimvar labelPrimvar(api.CreateStepLabelAttr());
            labelPrimvar.SetInterpolation(UsdGeomTokens->constant);
            labelPrimvar.Set(TfToken(entry.ToCString()));

            completed++;
            if (Logger::activeLevel == Logger::DEBUG) {
                LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Writing Assembly Override: " + protoPath.GetString());
            } else {
                LOG_PROGRESS(completed, total, "Writing Prototype Overrides");
            }
        }
    } // SdfChangeBlock

    LOG_PROGRESS_DONE();
}

// MARK: - Prototype Geometry

// MARK: Mesh
static void defineMeshGeometry(
    UsdStageRefPtr stage,
    const SdfPath& protoPath,
    const TessResult& r,
    const TessParams& params
) {
    UsdGeomMesh proto = UsdGeomMesh::Define(stage, protoPath.AppendChild(TfToken("Mesh")));

    if (params.meshEnableSurfaceSubsets) {
        for (const auto& surfaceIDBounds : r.surfaceIDBounds) {
            UsdGeomSubset::Define(
                stage,
                proto.GetPath().AppendChild(TfToken("SurfaceSubset_" + std::to_string(surfaceIDBounds.surfaceID)))
            );
        }
    }
    
    UsdGeomPrimvarsAPI api(proto);
    api.CreatePrimvar(TfToken("st"), SdfValueTypeNames->TexCoord2fArray, UsdGeomTokens->faceVarying);
    api.CreatePrimvar(TfToken("isBoundaryVertex"), SdfValueTypeNames->BoolArray, UsdGeomTokens->vertex);
    api.CreatePrimvar(TfToken("boundaryTangent"), SdfValueTypeNames->Normal3fArray, UsdGeomTokens->vertex);
}

static void writeMeshGeometry(
    UsdStageRefPtr stage,
    const SdfPath& protoPath,
    const TessResult& r,
    const TessParams& params
) {
    UsdGeomMesh proto(stage->GetPrimAtPath(protoPath.AppendChild(TfToken("Mesh"))));


    if (params.meshEnableSurfaceSubsets) {
        for (const auto& surfaceIDBounds : r.surfaceIDBounds) {
            int count = surfaceIDBounds.endIdx - surfaceIDBounds.startIdx;

            VtIntArray indices(count);
            std::iota(indices.begin(), indices.end(), surfaceIDBounds.startIdx);
            
            UsdGeomSubset subset(stage->GetPrimAtPath(proto.GetPath().AppendChild(TfToken("SurfaceSubset_" + std::to_string(surfaceIDBounds.surfaceID)))));

            if (!subset) {
                LOG_ERR("writeMeshGeometry: missing subset prim SurfaceSubset_" + std::to_string(surfaceIDBounds.surfaceID));
                continue;
            }

            subset.CreateElementTypeAttr().Set(UsdGeomTokens->face);
            subset.CreateIndicesAttr().Set(indices);
            subset.CreateFamilyNameAttr().Set(TfToken("materialBind"));
        }
        
        UsdGeomSubset::SetFamilyType(proto, TfToken("materialBind"), UsdGeomTokens->partition);
    }

    proto.GetPointsAttr().Set(r.points);
    proto.GetFaceVertexCountsAttr().Set(r.faceVertexCounts);
    proto.GetFaceVertexIndicesAttr().Set(r.faceVertexIndices);
    proto.GetSubdivisionSchemeAttr().Set(UsdGeomTokens->none);
    proto.SetNormalsInterpolation(UsdGeomTokens->faceVarying);
    proto.GetNormalsAttr().Set(r.normals);

    {
        VtVec3fArray extent(2);
        if (UsdGeomPointBased::ComputeExtent(r.points, &extent)) {
            proto.CreateExtentAttr().Set(extent);
        } else {
            LOG_ERR("writeMeshGeometry: ComputeExtent failed at " + protoPath.GetString());
        }
    }

    UsdGeomPrimvarsAPI api(proto);
    if (params.meshEnableUVs) if (UsdGeomPrimvar p = api.GetPrimvar(TfToken("st"))) p.Set(r.perSurfaceUVs);
    if (params.meshEnableIsBoundaryVertex) if (UsdGeomPrimvar p = api.GetPrimvar(TfToken("isBoundaryVertex"))) p.Set(r.isBoundaryVertex);
    if (!r.boundaryTangents.empty() && r.boundaryTangents.size() == r.points.size()) {
        if (UsdGeomPrimvar p = api.GetPrimvar(TfToken("boundaryTangent")))
            p.Set(r.boundaryTangents);
    }
}

struct CurvePiece {
    int sourceCurveIdx; // index into original counts/continuity array
    int pointOffset;    // offset into points array
    int pointCount;     // length of this piece (<= pointLimit)
};

// Split each original curve into pieces no longer than pointLimit.
// For oversized curves, each continuation piece repeats the previous
// piece's endpoint as its first point to avoid visual gaps.
static std::vector<CurvePiece> splitCurvesIntoPieces(const VtIntArray& counts, uint64_t pointLimit) {
    std::vector<CurvePiece> pieces;
    int pointOffset = 0;

    if (pointLimit == 0) {
        return pieces;
    }

    for (size_t curveIdx = 0; curveIdx < counts.size(); ++curveIdx) {
        int curveCount = counts[curveIdx];
        if (curveCount <= 0) {
            continue;
        }

        if ((uint64_t)curveCount <= pointLimit || pointLimit == 1) {
            int remaining = curveCount;
            int offset = pointOffset;
            while (remaining > 0) {
                int take = (int)std::min((uint64_t)remaining, pointLimit);
                pieces.push_back({(int)curveIdx, offset, take});
                offset += take;
                remaining -= take;
            }
            pointOffset += curveCount;
            continue;
        }

        int consumed = 0;

        // First piece uses up to pointLimit unique points.
        int firstCount = (int)std::min((uint64_t)curveCount, pointLimit);
        pieces.push_back({(int)curveIdx, pointOffset, firstCount});
        consumed += firstCount;

        // Remaining pieces repeat the previous endpoint, then add up to
        // (pointLimit - 1) new points.
        while (consumed < curveCount) {
            int remainingUnique = curveCount - consumed;
            int takeUnique = (int)std::min((uint64_t)remainingUnique, pointLimit - 1);

            int pieceStart = pointOffset + consumed - 1;
            int pieceCount = 1 + takeUnique;
            pieces.push_back({(int)curveIdx, pieceStart, pieceCount});

            consumed += takeUnique;
        }

        pointOffset += curveCount;
    }
    return pieces;
}

struct CurveChunk {
    std::vector<CurvePiece> pieces;
    int pointOffset; // == pieces.front().pointOffset
    int pointCount;  // sum of piece pointCounts
};

// Group pieces into prim-sized chunks. If combine==false, each piece is its own chunk.
static std::vector<CurveChunk> computeCurveChunks(const VtIntArray& counts, uint64_t pointLimit, bool combine) {
    std::vector<CurvePiece> pieces = splitCurvesIntoPieces(counts, pointLimit);
    std::vector<CurveChunk> chunks;

    if (!combine) {
        for (const auto& piece : pieces) {
            chunks.push_back({{piece}, piece.pointOffset, piece.pointCount});
        }
        return chunks;
    }

    size_t i = 0;
    while (i < pieces.size()) {
        CurveChunk chunk;
        chunk.pointOffset = pieces[i].pointOffset;
        chunk.pointCount = 0;
        while (i < pieces.size()) {
            int c = pieces[i].pointCount;
            if (!chunk.pieces.empty() && (uint64_t)(chunk.pointCount + c) > pointLimit) break;
            chunk.pieces.push_back(pieces[i]);
            chunk.pointCount += c;
            i++;
        }
        chunks.push_back(chunk);
    }
    return chunks;
}

static VtIntArray chunkVertexCounts(const CurveChunk& chunk) {
    VtIntArray counts(chunk.pieces.size());
    for (size_t j = 0; j < chunk.pieces.size(); ++j) counts[j] = chunk.pieces[j].pointCount;
    return counts;
}

template <typename T>
static VtArray<T> gatherChunkValues(const VtArray<T>& source, const CurveChunk& chunk) {
    std::vector<T> values;
    for (const auto& piece : chunk.pieces) {
        if (piece.pointCount <= 0 || piece.pointOffset < 0) {
            continue;
        }

        int end = piece.pointOffset + piece.pointCount;
        if (end > (int)source.size()) {
            continue;
        }

        values.insert(
            values.end(),
            source.begin() + piece.pointOffset,
            source.begin() + end
        );
    }
    return VtArray<T>(values.begin(), values.end());
}

// MARK: Wireframe
static void defineWireframeGeometry(
    UsdStageRefPtr stage,
    const SdfPath& protoPath,
    const TessResult& r,
    const TessParams& params
) {
    SdfPath wireframePath = protoPath.AppendChild(TfToken("Wireframe"));
    UsdGeomXform::Define(stage, wireframePath);

    if (params.wireframePointLimit <= 0) {
        LOG_ERR("Prim: " + protoPath.GetString() + ": defineWireframeGeometry: invalid wireframePointLimit " + std::to_string(params.wireframePointLimit) + ", must be > 0.");
        return;
    }

    uint64_t numSubCurves = (r.wireframePoints.size() + params.wireframePointLimit - 1) / params.wireframePointLimit;

    if (params.wireframeCombineCurves && numSubCurves == 1) {
        UsdGeomBasisCurves curve = UsdGeomBasisCurves::Define(
            stage, wireframePath.AppendChild(TfToken("Curves"))
        );
        if (!r.wireframeContinuity.empty()) {
            UsdGeomPrimvarsAPI(curve).CreatePrimvar(TfToken("continuityType"), SdfValueTypeNames->IntArray, UsdGeomTokens->uniform);
        }
        if (params.wireframeEmbedSurfaceNormals && r.wireframeSurfaceNormals.size() == r.wireframePoints.size()) {
            UsdGeomPrimvarsAPI(curve).CreatePrimvar(TfToken("surfaceNormal"), SdfValueTypeNames->Normal3fArray, UsdGeomTokens->vertex);
        }

        if (params.wireframeEmbedSurfaceNormals && r.wireframeSurfaceNormals.size() == r.wireframePoints.size()) {
            LOG_DEBUG("defineWireframeGeometry: Created surfaceNormal primvar for wireframe");
        }
        if (r.wireframeArcValues.size() == r.wireframePoints.size()) {
            UsdGeomPrimvarsAPI(curve).CreatePrimvar(TfToken("uArc"), SdfValueTypeNames->FloatArray, UsdGeomTokens->vertex);
        }
    } else {
        std::vector<CurveChunk> chunks = computeCurveChunks(r.wireframeCounts, params.wireframePointLimit, params.wireframeCombineCurves);

        for (size_t ci = 0; ci < chunks.size(); ++ci) {
            UsdGeomBasisCurves curve = UsdGeomBasisCurves::Define(
                stage, wireframePath.AppendChild(TfToken("Wireframe_" + std::to_string(ci)))
            );

            if (!r.wireframeContinuity.empty()) {
                UsdGeomPrimvarsAPI(curve).CreatePrimvar(TfToken("continuityType"), SdfValueTypeNames->IntArray, UsdGeomTokens->uniform);
            }
            if (params.wireframeEmbedSurfaceNormals && r.wireframeSurfaceNormals.size() == r.wireframePoints.size()) {
                UsdGeomPrimvarsAPI(curve).CreatePrimvar(TfToken("surfaceNormal"), SdfValueTypeNames->Normal3fArray, UsdGeomTokens->vertex);
            }
            if (!r.wireframeArcValues.empty()) {
                UsdGeomPrimvarsAPI(curve).CreatePrimvar(TfToken("uArc"), SdfValueTypeNames->FloatArray, UsdGeomTokens->vertex);
            }
        }
    }
}

static void writeWireframeGeometry(
    UsdStageRefPtr stage,
    const SdfPath& protoPath,
    const TessResult& r,
    const TessParams& params
) {
    SdfPath wireframePath = protoPath.AppendChild(TfToken("Wireframe"));

    if (params.wireframePointLimit <= 0) {
        LOG_ERR("Prim: " + protoPath.GetString() + ": defineWireframeGeometry: invalid wireframePointLimit " + std::to_string(params.wireframePointLimit) + ", must be > 0.");
        return;
    }
    
    uint64_t numSubCurves = (r.wireframePoints.size() + params.wireframePointLimit - 1) / params.wireframePointLimit;

    if (params.wireframeCombineCurves && numSubCurves == 1) {
        UsdGeomBasisCurves curve(stage->GetPrimAtPath(wireframePath.AppendChild(TfToken("Curves"))));

        if (!curve) {
            LOG_ERR("writeWireframeGeometry: missing curve prim");
            return;
        }

        if (params.wireframeMode.type == TessParams::CurveType::Cubic) {
            curve.CreateTypeAttr().Set(UsdGeomTokens->cubic);
            curve.CreateBasisAttr().Set(UsdGeomTokens->catmullRom);
        } else {
            curve.CreateTypeAttr().Set(UsdGeomTokens->linear);
        }
        curve.CreateWrapAttr().Set(UsdGeomTokens->nonperiodic);
        curve.GetPointsAttr().Set(r.wireframePoints);
        curve.GetCurveVertexCountsAttr().Set(r.wireframeCounts);

        {
            VtVec3fArray extent(2);
            if (UsdGeomPointBased::ComputeExtent(r.wireframePoints, &extent)) {
                curve.CreateExtentAttr().Set(extent);
            } else {
                LOG_ERR("writeWireframeGeometry: ComputeExtent failed at " + protoPath.GetString());
            }
        }
        
        //curve.CreateWidthsAttr().Set(VtArray<float>{0.005f});
        //UsdGeomPrimvarsAPI(curve).CreatePrimvar(TfToken("widths"), SdfValueTypeNames->FloatArray, UsdGeomTokens->constant).Set(VtArray<float>{0.005f});
        
        curve.GetDisplayColorAttr().Set(VtArray<GfVec3f>{{0.8f, 0.8f, 0.8f}});

        if (!r.wireframeContinuity.empty()) {
            UsdGeomPrimvarsAPI api(curve);
            if (UsdGeomPrimvar p = api.GetPrimvar(TfToken("continuityType"))) p.Set(r.wireframeContinuity);
        }

        if (params.wireframeEmbedSurfaceNormals && r.wireframeSurfaceNormals.size() == r.wireframePoints.size() && !r.points.empty()) {
            UsdGeomPrimvarsAPI api(curve);
            if (UsdGeomPrimvar p = api.GetPrimvar(TfToken("surfaceNormal")))
                p.Set(r.wireframeSurfaceNormals);
        }

        if (r.wireframeArcValues.size() == r.wireframePoints.size()) {
            UsdGeomPrimvarsAPI api(curve);
            if (UsdGeomPrimvar p = api.GetPrimvar(TfToken("uArc"))) 
                p.Set(r.wireframeArcValues);
        }
    } else {
        std::vector<CurveChunk> chunks = computeCurveChunks(r.wireframeCounts, params.wireframePointLimit, params.wireframeCombineCurves);

        for (size_t ci = 0; ci < chunks.size(); ++ci) {
            const CurveChunk& chunk = chunks[ci];

            UsdGeomBasisCurves curve(stage->GetPrimAtPath(wireframePath.AppendChild(TfToken("Wireframe_" + std::to_string(ci)))));
            if (!curve) {
                LOG_ERR("writeWireframeGeometry: missing curve prim Wireframe_" + std::to_string(ci));
                continue;
            }

            if (params.wireframeMode.type == TessParams::CurveType::Cubic) {
                curve.CreateTypeAttr().Set(UsdGeomTokens->cubic);
                curve.CreateBasisAttr().Set(UsdGeomTokens->catmullRom);
            } else {
                curve.CreateTypeAttr().Set(UsdGeomTokens->linear);
            }
            curve.CreateWrapAttr().Set(UsdGeomTokens->nonperiodic);

            VtArray<GfVec3f> pts = gatherChunkValues(r.wireframePoints, chunk);
            curve.GetPointsAttr().Set(pts);
            curve.GetCurveVertexCountsAttr().Set(chunkVertexCounts(chunk));
            curve.GetDisplayColorAttr().Set(VtArray<GfVec3f>{{0.8f, 0.8f, 0.8f}});

            {
                VtVec3fArray extent(2);
                if (UsdGeomPointBased::ComputeExtent(r.points, &extent)) {
                    curve.CreateExtentAttr().Set(extent);
                } else {
                    LOG_ERR("writeMeshGeometry: ComputeExtent failed at " + protoPath.GetString());
                }
            }

            UsdGeomPrimvarsAPI api(curve);

            if (!r.wireframeContinuity.empty()) {
                VtIntArray continuity(chunk.pieces.size());
                for (size_t j = 0; j < chunk.pieces.size(); ++j) {
                    int srcIdx = chunk.pieces[j].sourceCurveIdx;
                    continuity[j] = (srcIdx < (int)r.wireframeContinuity.size()) ? r.wireframeContinuity[srcIdx] : 0;
                }
                if (UsdGeomPrimvar p = api.GetPrimvar(TfToken("continuityType")))
                    p.Set(continuity);
            }

            if (!r.wireframeArcValues.empty()) {
                VtArray<float> arcUs = gatherChunkValues(r.wireframeArcValues, chunk);
                if (UsdGeomPrimvar p = api.GetPrimvar(TfToken("uArc")))
                    p.Set(arcUs);
            }

            if (params.wireframeEmbedSurfaceNormals && !r.wireframeSurfaceNormals.empty()) {
                VtArray<GfVec3f> normals = gatherChunkValues(r.wireframeSurfaceNormals, chunk);
                if (UsdGeomPrimvar p = api.GetPrimvar(TfToken("surfaceNormal")))
                    p.Set(normals);
            }
        }
    }
}

// MARK: Sketch
static void defineSketchGeometry(
    UsdStageRefPtr stage,
    const SdfPath& protoPath,
    const TessResult& r,
    const TessParams& params
) {
    SdfPath sketchPath = protoPath.AppendChild(TfToken("Sketch"));
    UsdGeomScope::Define(stage, sketchPath);

    if (params.sketchPointLimit <= 0) {
        LOG_ERR("Prim: " + protoPath.GetString() + ": defineSketchGeometry: invalid sketchPointLimit " + std::to_string(params.sketchPointLimit) + ", must be > 0.");
        return;
    }

    uint64_t numSubCurves = (r.sketchPoints.size() + params.sketchPointLimit - 1) / params.sketchPointLimit;

    if (params.sketchCombineCurves && numSubCurves == 1) {
        UsdGeomBasisCurves curves = UsdGeomBasisCurves::Define(
            stage, sketchPath.AppendChild(TfToken("Curves"))
        );
        if (!r.sketchArcValues.empty()) {
            UsdGeomPrimvarsAPI(curves).CreatePrimvar(
                TfToken("uArc"), SdfValueTypeNames->FloatArray, UsdGeomTokens->vertex
            );
        }
    } else {
        std::vector<CurveChunk> chunks = computeCurveChunks(r.sketchCounts, params.sketchPointLimit, params.sketchCombineCurves);

        for (size_t ci = 0; ci < chunks.size(); ++ci) {
            UsdGeomBasisCurves sketchCurve = UsdGeomBasisCurves::Define(
                stage, sketchPath.AppendChild(TfToken("Curve_" + std::to_string(ci)))
            );

            if (!r.sketchArcValues.empty()) {
                UsdGeomPrimvarsAPI(sketchCurve).CreatePrimvar(
                    TfToken("uArc"), SdfValueTypeNames->FloatArray, UsdGeomTokens->vertex
                );
            }
        }
    }
}

static void writeSketchGeometry(
    UsdStageRefPtr stage,
    const SdfPath& protoPath,
    const TessResult& r,
    const TessParams& params
) {
    SdfPath sketchPath = protoPath.AppendChild(TfToken("Sketch"));

    if (params.sketchPointLimit <= 0) {
        LOG_ERR("Prim: " + protoPath.GetString() + ": defineSketchGeometry: invalid sketchPointLimit " + std::to_string(params.sketchPointLimit) + ", must be > 0.");
        return;
    }

    uint64_t numSubCurves = (r.sketchPoints.size() + params.sketchPointLimit - 1) / params.sketchPointLimit;

    if (params.sketchCombineCurves && numSubCurves == 1) {
        UsdGeomBasisCurves sketchCurve(stage->GetPrimAtPath(sketchPath.AppendChild(TfToken("Curves"))));

        if (!sketchCurve) {
            LOG_ERR("writeSketchGeometry: missing curve prim");
            return;
        }

        if (params.sketchMode.type == TessParams::CurveType::Cubic) {
            sketchCurve.CreateTypeAttr().Set(UsdGeomTokens->cubic);
            sketchCurve.CreateBasisAttr().Set(UsdGeomTokens->catmullRom);
        } else {
            sketchCurve.CreateTypeAttr().Set(UsdGeomTokens->linear);
        }
        sketchCurve.CreateWrapAttr().Set(UsdGeomTokens->nonperiodic);
        sketchCurve.GetPointsAttr().Set(r.sketchPoints);
        sketchCurve.GetCurveVertexCountsAttr().Set(r.sketchCounts);

        {
            VtVec3fArray extent(2);
            if (UsdGeomPointBased::ComputeExtent(r.sketchPoints, &extent)) {
                sketchCurve.CreateExtentAttr().Set(extent);
            } else {
                LOG_ERR("writeSketchGeometry: ComputeExtent failed at " + protoPath.GetString());
            }
        }

        if (r.sketchArcValues.size() == r.sketchPoints.size()) {
            UsdGeomPrimvarsAPI(sketchCurve).CreatePrimvar(TfToken("uArc"), SdfValueTypeNames->FloatArray, UsdGeomTokens->vertex);
        }
        
        if (r.sketchArcValues.size() == r.sketchPoints.size()) {
            UsdGeomPrimvarsAPI api(sketchCurve);
            if (UsdGeomPrimvar p = api.GetPrimvar(TfToken("uArc")))
                p.Set(r.sketchArcValues);
        }

        //sketchCurve.CreateWidthsAttr().Set(VtArray<float>{0.005f});
        //UsdGeomPrimvarsAPI(sketchCurve).CreatePrimvar(TfToken("widths"), SdfValueTypeNames->FloatArray, UsdGeomTokens->constant).Set(VtArray<float>{0.005f});
        
        sketchCurve.GetDisplayColorAttr().Set(VtArray<GfVec3f>{{0.4f, 0.7f, 1.0f}});
    } else {
        std::vector<CurveChunk> chunks = computeCurveChunks(r.sketchCounts, params.sketchPointLimit, params.sketchCombineCurves);

        for (size_t ci = 0; ci < chunks.size(); ++ci) {
            const CurveChunk& chunk = chunks[ci];

            UsdGeomBasisCurves sketchCurve(stage->GetPrimAtPath(sketchPath.AppendChild(TfToken("Curve_" + std::to_string(ci)))));
            if (!sketchCurve) {
                LOG_ERR("writeSketchGeometry: missing curve prim Curve_" + std::to_string(ci));
                continue;
            }

            if (params.sketchMode.type == TessParams::CurveType::Cubic) {
                sketchCurve.CreateTypeAttr().Set(UsdGeomTokens->cubic);
                sketchCurve.CreateBasisAttr().Set(UsdGeomTokens->catmullRom);
            } else {
                sketchCurve.CreateTypeAttr().Set(UsdGeomTokens->linear);
            }
            sketchCurve.CreateWrapAttr().Set(UsdGeomTokens->nonperiodic);

            VtArray<GfVec3f> pts = gatherChunkValues(r.sketchPoints, chunk);
            sketchCurve.GetPointsAttr().Set(pts);
            sketchCurve.GetCurveVertexCountsAttr().Set(chunkVertexCounts(chunk));
            sketchCurve.GetDisplayColorAttr().Set(VtArray<GfVec3f>{{0.4f, 0.7f, 1.0f}});

            {
                VtVec3fArray extent(2);
                if (UsdGeomPointBased::ComputeExtent(r.points, &extent)) {
                    sketchCurve.CreateExtentAttr().Set(extent);
                } else {
                    LOG_ERR("writeMeshGeometry: ComputeExtent failed at " + protoPath.GetString());
                }
            }

            if (!r.sketchArcValues.empty()) {
                VtArray<float> arcUs = gatherChunkValues(r.sketchArcValues, chunk);
                UsdGeomPrimvarsAPI api(sketchCurve);
                if (UsdGeomPrimvar p = api.GetPrimvar(TfToken("uArc")))
                    p.Set(arcUs);
            }
        }
    }
}

// MARK: SketchPlane
static void defineSketchPlaneGeometry(
    UsdStageRefPtr stage,
    const SdfPath& protoPath,
    const TessResult& r,
    const TessParams& params
) {
    SdfPath sketchPlanesPath = protoPath.AppendChild(TfToken("SketchPlanes"));
    UsdGeomScope::Define(stage, sketchPlanesPath);
    for (size_t pi = 0; pi < r.sketchPlaneBounds.size(); ++pi) {
        UsdGeomMesh::Define(stage, sketchPlanesPath.AppendChild(TfToken("Plane_" + std::to_string(pi))));
    }
}

static void writeSketchPlaneGeometry(
    UsdStageRefPtr stage,
    const SdfPath& protoPath,
    const TessResult& r,
    const TessParams& params
) {
    SdfPath sketchPlanesPath = protoPath.AppendChild(TfToken("SketchPlanes"));

    for (size_t pi = 0; pi < r.sketchPlaneBounds.size(); ++pi) {
        const TessResult::SketchPlaneBounds& b = r.sketchPlaneBounds[pi];

        if (b.pointStart < 0 || b.pointCount <= 0 ||
            b.faceCountStart < 0 || b.faceCountCount <= 0 ||
            b.faceIndexStart < 0 || b.faceIndexCount <= 0 ||
            b.normalStart < 0 || b.normalCount <= 0) {
            continue;
        }

        if (static_cast<size_t>(b.pointStart + b.pointCount) > r.sketchPlanePoints.size() ||
            static_cast<size_t>(b.faceCountStart + b.faceCountCount) > r.sketchPlaneFaceVertexCounts.size() ||
            static_cast<size_t>(b.faceIndexStart + b.faceIndexCount) > r.sketchPlaneFaceVertexIndices.size() ||
            static_cast<size_t>(b.normalStart + b.normalCount) > r.sketchPlaneNormals.size()) {
            continue;
        }

        // Build a compact point array and remap indices in one pass.
        // The stored indices are absolute into sketchPlanePoints; we need
        // them rebased to a local [0, N) range for this plane's mesh prim.
        std::unordered_map<int, int> globalToLocal;
        VtArray<GfVec3f> points;
        VtArray<GfVec3f> normals;

        VtArray<int> counts(
            r.sketchPlaneFaceVertexCounts.begin() + b.faceCountStart,
            r.sketchPlaneFaceVertexCounts.begin() + b.faceCountStart + b.faceCountCount
        );

        VtArray<int> indices;
        indices.reserve(b.faceIndexCount);

        bool corruptPlane = false;
        for (int fi = b.faceIndexStart; fi < b.faceIndexStart + b.faceIndexCount; ++fi) {
            int globalIdx = r.sketchPlaneFaceVertexIndices[fi];

            auto [it, inserted] = globalToLocal.emplace(globalIdx, (int)points.size());
            if (inserted) {
                if (static_cast<size_t>(globalIdx) >= r.sketchPlanePoints.size()) {
                    // Corrupt index — skip entire plane
                    corruptPlane = true;
                    continue;
                }
                points.push_back(r.sketchPlanePoints[globalIdx]);
            }
            indices.push_back(it->second);
        }

        if (corruptPlane) continue; 

        // Normals are faceVarying (one per face-vertex), slice directly
        normals = VtArray<GfVec3f>(
            r.sketchPlaneNormals.begin() + b.normalStart,
            r.sketchPlaneNormals.begin() + b.normalStart + b.normalCount
        );

        {
            UsdGeomMesh mesh(stage->GetPrimAtPath(
                sketchPlanesPath.AppendChild(TfToken("Plane_" + std::to_string(pi)))
            ));
            mesh.GetPointsAttr().Set(points);
            mesh.GetFaceVertexCountsAttr().Set(counts);
            mesh.GetFaceVertexIndicesAttr().Set(indices);
            mesh.GetSubdivisionSchemeAttr().Set(UsdGeomTokens->none);
            mesh.SetNormalsInterpolation(UsdGeomTokens->faceVarying);
            mesh.GetNormalsAttr().Set(normals);
            mesh.GetDisplayColorAttr().Set(VtArray<GfVec3f>{{0.55f, 0.8f, 1.0f}});
        }
    }
}

// rotation block: transposed relative to OCC Value(row,col) convention
// translation: from TranslationPart() into the last row
static GfMatrix4d trsfToGfMatrix(const gp_Trsf& t, double linearScale) {
    gp_XYZ trans = t.TranslationPart();
    auto clean = [](double v) { return std::abs(v) < 1e-10 ? 0.0 : v; };
    return GfMatrix4d(
        clean(t.Value(1,1)), clean(t.Value(2,1)), clean(t.Value(3,1)), 0.0,
        clean(t.Value(1,2)), clean(t.Value(2,2)), clean(t.Value(3,2)), 0.0,
        clean(t.Value(1,3)), clean(t.Value(2,3)), clean(t.Value(3,3)), 0.0,
        clean(trans.X() * linearScale),
        clean(trans.Y() * linearScale),
        clean(trans.Z() * linearScale),
        1.0
    );
}

// Assembly Xforms
void StepUsdPipeline::writeAssemblyXforms(
    UsdStageRefPtr stage, 
    const std::vector<OpenCascadeAssembly::PartNode>& partNodes,
    const std::vector<SdfPath>& paths, 
    const LabelMap<SdfPath>& prototypePaths,
    double linearScale
) {
    LOG_SCOPED_TIMER("writeAssemblyXforms (" + std::to_string(partNodes.size()) + " nodes)");
    
    // pre compute which instances have children
    std::vector<bool> hasChildren(partNodes.size(), false);
    for (size_t i = 0; i < partNodes.size(); i++) {
        if (partNodes[i].parentIdx != -1)
            hasChildren[partNodes[i].parentIdx] = true;
    }
    // Define all xform nodes, wire references, and author transforms
    const int total = (int)partNodes.size();
    int completed = 0;
    for (size_t i = 0; i < partNodes.size(); i++) {
        const OpenCascadeAssembly::PartNode& node = partNodes[i];
        UsdGeomXform xform = UsdGeomXform::Define(stage, paths[i]);
        if (!xform) {
            std::cerr << "[" << i << "] Failed to define Xform at " << paths[i] << "\n";
            completed++;
            if (Logger::activeLevel == Logger::DEBUG) {
                LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Failed to write Assembly Xform for " + paths[i].GetString());
            } else {
                LOG_PROGRESS(completed, total, "Writing Assembly");
            }
            continue;
        }
        {
            SdfChangeBlock changeBlock;

            TCollection_AsciiString entry;
            TDF_Tool::Entry(node.instanceLabel, entry);
            
            AutolibStepAPI api(xform.GetPrim());
            api.CreateStepLabelAttr().Set(TfToken(entry.ToCString()));

            if (!node.name.empty() && !isAutoGeneratedName(node.name)) {
                xform.GetPrim().SetDisplayName(node.name);
            } else {
                // no real name — display the hash portion only, without the leading __
                std::string pathName = paths[i].GetName();
                if (pathName.size() > 2 && pathName[0] == '_' && pathName[1] == '_') {
                    xform.GetPrim().SetDisplayName(pathName.substr(2));
                }
            }
            
            // Usd composes the full world transform later
            xform.AddTransformOp().Set(trsfToGfMatrix(node.localTransform, linearScale));
            if (node.type == OpenCascadeAssembly::PartNodeType::Leaf) {
                auto protoIter = prototypePaths.find(node.definitionLabel);
                if (protoIter == prototypePaths.end()) {
                    completed++;
                    if (Logger::activeLevel == Logger::DEBUG) {
                        LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Skip missing prototype Assembly Xform: " + paths[i].GetString());
                    } else {
                        LOG_PROGRESS(completed, total, "Writing Assembly");
                    }
                    continue;
                }

                const SdfPath& assemblyProtoPath = protoIter->second;

                xform.GetPrim().GetReferences().AddInternalReference(assemblyProtoPath);
                UsdModelAPI(xform.GetPrim()).SetKind(TfToken("component"));
                if (!hasChildren[i]) {
                    xform.GetPrim().SetInstanceable(true);
                }
                UsdGeomImageable api(xform.GetPrim());
                api.GetVisibilityAttr().Set(UsdGeomTokens->inherited);
                if (node.color.has_value()) { // TODO: Support muliple colors per mesh
                    VtArray<GfVec3f> displayColor = {{
                        static_cast<float>(node.color->Red()),
                        static_cast<float>(node.color->Green()),
                        static_cast<float>(node.color->Blue())
                    }};
                    UsdAttribute colorAttr = xform.GetPrim().CreateAttribute(
                        TfToken("primvars:displayColor"),
                        SdfValueTypeNames->Color3fArray,
                        false
                    );
                    colorAttr.Set(displayColor);
                    UsdGeomPrimvar labelPrimvar(colorAttr);
                    labelPrimvar.SetInterpolation(UsdGeomTokens->constant);
                }
                if (!node.visible) {
                    UsdGeomImageable(xform.GetPrim())
                        .CreateVisibilityAttr()
                        .Set(UsdGeomTokens->invisible);
                }
            } else {
                UsdModelAPI(xform.GetPrim()).SetKind(TfToken("assembly"));
            }
        } // SdfChangeBlock
        completed++;
        if (Logger::activeLevel == Logger::DEBUG) {
            LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Writing Assembly: " + paths[i].GetString());
        } else {
            LOG_PROGRESS(completed, total, "Writing Assembly");
        }
    }
    LOG_PROGRESS_DONE();
}

void StepUsdPipeline::writePrototypeGeometries(
    UsdStageRefPtr stage,
    const std::vector<ProtoGeomJob>& inJobs,
    const std::unordered_set<SdfPath, SdfPath::Hash>& selectedPaths,
    const std::string& variantSetName,
    const std::string& variantName
) {
    const int total = (int)inJobs.size();
    if (total == 0) return;

    // Create a mutable copy of the jobs vector 
    // so we can sort it for load balancing
    std::vector<ProtoGeomJob> jobs = inJobs;
    std::sort(jobs.begin(), jobs.end(), [](const ProtoGeomJob& a, const ProtoGeomJob& b) {
        // Sort descending by number of points to process larger geometries first
        return a.result.points.size() > b.result.points.size();
    });

    std::atomic<int> completed(0);
    std::string logLabel = "";
    if (!variantSetName.empty()) {
        logLabel = " {" + variantSetName + "=" + variantName + "}";
    }

    struct ThreadResult {
        int startIdx;
        int endIdx;
        SdfLayerRefPtr layer;
    };

    std::vector<ThreadResult> threadResults;
    std::mutex resultsMutex;

    const int grainSize = 1;

    WorkParallelForN(total, [&](int startIdx, int endIdx) {
        TfErrorMark mark;
        SdfLayerRefPtr threadLayer = SdfLayer::CreateAnonymous();
        UsdStageRefPtr threadStage = UsdStage::Open(threadLayer);

        // their properties are later populated in the SdfChangeBlock 
        for (int i = startIdx; i < endIdx; i++) {
            const SdfPath& protoPath = jobs[i].protoPath;
            const TessResult& r = jobs[i].result;
            const TessParams& params = jobs[i].params;

            if (!selectedPaths.empty() && !isPrototypeActiveInFilter(selectedPaths, protoPath, variantSetName, variantName)) {
                continue;
            }

            UsdGeomScope protoXform;
                
            auto variantSelection = protoPath.GetVariantSelection();

            bool hasPoints = !r.points.empty() && !r.faceVertexIndices.empty() && !r.faceVertexCounts.empty();
            bool hasWireframe = !r.wireframePoints.empty() && !r.wireframeCounts.empty();
            bool hasSketch = !r.sketchPoints.empty() && !r.sketchCounts.empty();
            bool hasSketchPlanes = !r.sketchPlaneBounds.empty();
            
            if (!variantSelection.first.empty()) {
                SdfPath baseProtoPath = protoPath.StripAllVariantSelections();
                
                UsdPrim basePrim = threadStage->GetPrimAtPath(baseProtoPath);
                if (!basePrim) {
                    protoXform = UsdGeomScope::Define(threadStage, baseProtoPath);
                    basePrim = protoXform.GetPrim();
                } else {
                    protoXform = UsdGeomScope(basePrim);
                }
                
                UsdVariantSet vset = basePrim.GetVariantSets().AddVariantSet(variantSelection.first);
                vset.AddVariant(variantSelection.second);
                vset.SetVariantSelection(variantSelection.second);
                UsdEditContext ctx(vset.GetVariantEditContext());
                
                threadStage->RemovePrim(baseProtoPath.AppendChild(TfToken("Mesh")));
                threadStage->RemovePrim(baseProtoPath.AppendChild(TfToken("Wireframe")));
                threadStage->RemovePrim(baseProtoPath.AppendChild(TfToken("Sketch")));
                threadStage->RemovePrim(baseProtoPath.AppendChild(TfToken("SketchPlanes")));

                if (r.renderOnly) UsdGeomImageable(protoXform.GetPrim()).CreatePurposeAttr();

                if (hasPoints) defineMeshGeometry(threadStage, baseProtoPath, r, params);
                if (hasWireframe) defineWireframeGeometry(threadStage, baseProtoPath, r, params); 
                if (hasSketch) defineSketchGeometry(threadStage, baseProtoPath, r, params);
                if (hasSketchPlanes) defineSketchPlaneGeometry(threadStage, baseProtoPath, r, params);

            } else {
                protoXform = UsdGeomScope::Get(threadStage, protoPath);
                if (!protoXform) {
                    protoXform = UsdGeomScope::Define(threadStage, protoPath);
                }

                if (!protoXform) {
                    LOG_ERR("Failed to define scope at " + protoPath.GetString());
                    continue;
                }
                        
                threadStage->RemovePrim(protoPath.AppendChild(TfToken("Mesh")));
                threadStage->RemovePrim(protoPath.AppendChild(TfToken("Wireframe")));
                threadStage->RemovePrim(protoPath.AppendChild(TfToken("Sketch")));
                threadStage->RemovePrim(protoPath.AppendChild(TfToken("SketchPlanes")));

                if (r.renderOnly) UsdGeomImageable(protoXform.GetPrim()).CreatePurposeAttr(); 
                if (hasPoints) defineMeshGeometry(threadStage, protoPath, r, params);
                if (hasWireframe) defineWireframeGeometry(threadStage, protoPath, r, params);
                if (hasSketch) defineSketchGeometry(threadStage, protoPath, r, params);
                if (hasSketchPlanes) defineSketchPlaneGeometry(threadStage, protoPath, r, params);
            }
        }

        if (!mark.IsClean()) {
            for (const auto& error : mark) std::cerr << "Usd: " << error.GetCommentary() << "\n";
        }

        { // SdfChangeBlock
            SdfChangeBlock block;
            for (int i = startIdx; i < endIdx; i++) {
                const SdfPath& protoPath = jobs[i].protoPath;
                const TessResult& r = jobs[i].result;
                const TessParams& params = jobs[i].params;

                if (!selectedPaths.empty() && !isPrototypeActiveInFilter(selectedPaths, protoPath, variantSetName, variantName)) {
                    int c = ++completed;
                    if (Logger::activeLevel == Logger::DEBUG) {
                        //LOG_DEBUG("[" + std::to_string(c) + "/" + std::to_string(total) + "] Skip geometry (filtered): " + protoPath.GetString());
                    } else {
                        LOG_PROGRESS(c, total, "Writing geometry" + logLabel);
                    }
                    continue;
                }

                auto variantSelection = protoPath.GetVariantSelection();
                SdfPath writeProtoPath = variantSelection.first.empty() ? protoPath : protoPath.StripAllVariantSelections();
                
                // If variant selected, we need the edit context 
                // active to author values inside the variant
                std::optional<UsdEditContext> ctx;
                if (!variantSelection.first.empty()) {
                    UsdPrim basePrim = threadStage->GetPrimAtPath(writeProtoPath);
                    UsdVariantSet vset = basePrim.GetVariantSets().AddVariantSet(variantSelection.first);
                    vset.AddVariant(variantSelection.second);
                    vset.SetVariantSelection(variantSelection.second);
                    ctx.emplace(vset.GetVariantEditContext());
                }

                UsdGeomScope protoXform = UsdGeomScope::Get(threadStage, writeProtoPath);

                if (!protoXform) {
                    LOG_ERR("writePrototypeGeometries: protoXform invalid at " + writeProtoPath.GetString() + " — define pass was skipped or failed");
                    int c = ++completed;
                    LOG_PROGRESS(c, total, "Writing geometry" + logLabel);
                    continue;
                }

                bool hasPoints = !r.points.empty() && !r.faceVertexIndices.empty() && !r.faceVertexCounts.empty();
                bool hasWireframe = !r.wireframePoints.empty() && !r.wireframeCounts.empty();
                bool hasSketch = !r.sketchPoints.empty() && !r.sketchCounts.empty();
                bool hasSketchPlanes = !r.sketchPlaneBounds.empty();

                if (r.renderOnly) UsdGeomImageable(protoXform.GetPrim()).CreatePurposeAttr().Set(UsdGeomTokens->render); 

                if (hasPoints) writeMeshGeometry(threadStage, writeProtoPath, r, params);
                if (hasWireframe) writeWireframeGeometry(threadStage, writeProtoPath, r, params);
                if (hasSketch) writeSketchGeometry(threadStage, writeProtoPath, r, params);
                if (hasSketchPlanes) writeSketchPlaneGeometry(threadStage, writeProtoPath, r, params);

                int c = ++completed;
                if (Logger::activeLevel == Logger::DEBUG) {
                    LOG_DEBUG("[" + std::to_string(c) + "/" + std::to_string(total) + "] Writing geometry: " + protoPath.GetString());
                } else {
                    LOG_PROGRESS(c, total, "Writing geometry" + logLabel);
                }
            }
        } // SdfChangeBlock
        
        if (!mark.IsClean()) {
            for (const auto& error : mark) std::cerr << "Usd: " << error.GetCommentary() << "\n";
        }

        std::lock_guard<std::mutex> resLock(resultsMutex);
        threadResults.push_back({startIdx, endIdx, threadLayer});
    }, grainSize);

    // Merge back on the main stage

    // There are two passes here to handle variant and non-variant geometry separately 
    // SdfCopy doesn't handle copying into variant bodies, so geometry under variants 
    // is written directly to the main stage in a separate pass

    { // SdfChangeBlock
        SdfChangeBlock changeBlock;
        SdfLayerHandle mainLayer = stage->GetRootLayer();

        // pre-create variant specs in mainLayer so the variant bodies exist
        for (const auto& res : threadResults) {
            if (!res.layer) continue;
            for (size_t i = res.startIdx; i < res.endIdx; i++) {
                const SdfPath& protoPath = jobs[i].protoPath;
                auto variantSelection = protoPath.GetVariantSelection();
                if (variantSelection.first.empty()) continue; // skip variants 

                SdfPath baseProtoPath = protoPath.StripAllVariantSelections();
                SdfPrimSpecHandle primSpec = mainLayer->GetPrimAtPath(baseProtoPath);
                if (!primSpec) continue;

                SdfVariantSetSpecHandle vsetSpec;
                auto vsetProxy = primSpec->GetVariantSets();
                auto vsetIt = vsetProxy.find(variantSelection.first);
                if (vsetIt == vsetProxy.end()) {
                    vsetSpec = SdfVariantSetSpec::New(primSpec, variantSelection.first);
                    primSpec->GetVariantSetNameList().Prepend(variantSelection.first);
                } else {
                    vsetSpec = vsetIt->second;
                }

                auto variantProxy = vsetSpec->GetVariants();
                if (variantProxy.find(variantSelection.second) == variantProxy.end()) {
                    SdfVariantSpec::New(vsetSpec, variantSelection.second);
                }
            }
        }

        // write the non variants
        for (const auto& res : threadResults) {
            if (!res.layer) continue;
            for (size_t i = res.startIdx; i < res.endIdx; i++) {
                const SdfPath& protoPath = jobs[i].protoPath;
                if (!selectedPaths.empty() && !isPrototypeActiveInFilter(selectedPaths, protoPath, variantSetName, variantName)) {
                    continue; // Skip filtered
                }
                if (!protoPath.GetVariantSelection().first.empty()) continue; // only non variants

                SdfPath copyPath = protoPath.GetVariantSelection().first.empty() ? protoPath : protoPath.StripAllVariantSelections();
                
                SdfPrimSpecHandle srcSpec = res.layer->GetPrimAtPath(copyPath);
                SdfPrimSpecHandle dstSpec = mainLayer->GetPrimAtPath(copyPath);
                if (srcSpec && dstSpec) {
                    dstSpec->SetTypeName(srcSpec->GetTypeName());
                    for (const auto& prop : srcSpec->GetProperties()) {
                        SdfCopySpec(res.layer, prop->GetPath(), mainLayer, prop->GetPath());
                    }
                    for (const auto& child : srcSpec->GetNameChildren()) {
                        SdfCopySpec(res.layer, child->GetPath(), mainLayer, child->GetPath());
                    }
                } else {
                    SdfCopySpec(res.layer, copyPath, mainLayer, copyPath);
                }
            }
        }
    } // SdfChangeBlock

    // Variant geometry written to main stage
    for (const auto& res : threadResults) {
        if (!res.layer) continue;
        for (size_t i = res.startIdx; i < res.endIdx; i++) {
            const SdfPath& protoPath = jobs[i].protoPath;
            if (!selectedPaths.empty() &&
                !isPrototypeActiveInFilter(selectedPaths, protoPath, variantSetName, variantName)) {
                continue;
            }

            auto variantSelection = protoPath.GetVariantSelection();
            if (variantSelection.first.empty()) continue;

            const TessResult& r = jobs[i].result;
            const TessParams& params = jobs[i].params;
            SdfPath baseProtoPath = protoPath.StripAllVariantSelections();

            UsdPrim basePrim = stage->GetPrimAtPath(baseProtoPath);
            if (!basePrim) {
                LOG_ERR("Missing base prim at " + baseProtoPath.GetString() + "\n");
                continue;
            }

            // t
            bool hasAuthoredActive = basePrim.GetPrim().HasAuthoredActive();
            bool initialActive = true;
            if (hasAuthoredActive) {
                initialActive = basePrim.GetPrim().IsActive();
                basePrim.GetPrim().SetActive(true);
            }

            UsdVariantSet vset = basePrim.GetVariantSets().AddVariantSet(variantSelection.first);
            vset.AddVariant(variantSelection.second);
            vset.SetVariantSelection(variantSelection.second);
            UsdEditContext ctx(vset.GetVariantEditContext());

            // Clear any previously written geometry under this variant
            stage->RemovePrim(baseProtoPath.AppendChild(TfToken("Mesh")));
            stage->RemovePrim(baseProtoPath.AppendChild(TfToken("Wireframe")));
            stage->RemovePrim(baseProtoPath.AppendChild(TfToken("Sketch")));
            stage->RemovePrim(baseProtoPath.AppendChild(TfToken("SketchPlanes")));

            if (r.renderOnly) {
                UsdPrim p = stage->GetPrimAtPath(baseProtoPath);
                if (p) {
                    UsdGeomImageable(p).CreatePurposeAttr().Set(UsdGeomTokens->render);
                }
            }

            bool hasPoints = !r.points.empty() && !r.faceVertexIndices.empty() && !r.faceVertexCounts.empty();
            bool hasWireframe = !r.wireframePoints.empty() && !r.wireframeCounts.empty();
            bool hasSketch = !r.sketchPoints.empty() && !r.sketchCounts.empty();
            bool hasSketchPlanes = !r.sketchPlaneBounds.empty();

            if (hasPoints) defineMeshGeometry(stage, baseProtoPath, r, params);
            if (hasWireframe) defineWireframeGeometry(stage, baseProtoPath, r, params);
            if (hasSketch) defineSketchGeometry(stage, baseProtoPath, r, params);
            if (hasSketchPlanes) defineSketchPlaneGeometry(stage, baseProtoPath, r, params);

            {
                SdfChangeBlock changeBlock;
                if (hasPoints) writeMeshGeometry(stage, baseProtoPath, r, params);
                if (hasWireframe) writeWireframeGeometry(stage, baseProtoPath, r, params);
                if (hasSketch) writeSketchGeometry(stage, baseProtoPath, r, params);
                if (hasSketchPlanes) writeSketchPlaneGeometry(stage, baseProtoPath, r, params);
            }

            if (hasAuthoredActive) {
                basePrim.GetPrim().SetActive(initialActive);
            } else {
                basePrim.GetPrim().ClearActive();
            }
        }
    }

    LOG_PROGRESS_DONE();
}