#include <ostream>
#include <iostream>
#include <utility>
#include <unordered_map>
#include <unordered_set>
#include <string>
#include <vector>
#include <mutex>
#include <atomic>

#include <TDF_Label.hxx>
#include <Quantity_Color.hxx>
#include <TopoDS_Shape.hxx>
#include <gp_XYZ.hxx>
#include <TDF_Tool.hxx>

#pragma push_macro("Handle")
#undef Handle

#include <pxr/pxr.h>
#include <pxr/usd/usd/common.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/modelAPI.h>
#include <pxr/usd/usd/inherits.h>
#include <pxr/usd/usd/attribute.h>
#include <pxr/usd/usd/references.h>
#include <pxr/usd/usd/variantSets.h>
#include <pxr/usd/usd/editContext.h>

#include <pxr/usd/sdf/changeBlock.h>
#include <pxr/usd/sdf/types.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/usd/sdf/variantSpec.h>
#include <pxr/usd/sdf/variantSetSpec.h>

#include <pxr/usd/usdGeom/mesh.h>
#include <pxr/usd/usdGeom/xform.h>
#include <pxr/usd/usdGeom/scope.h>
#include <pxr/usd/usdGeom/tokens.h>
#include <pxr/usd/usdGeom/primvarsAPI.h>
#include <pxr/usd/usdGeom/basisCurves.h>
#include <pxr/usd/usdGeom/imageable.h>
#include <pxr/usd/usdGeom/subset.h>
#include <pxr/usd/usdGeom/primvar.h>
#include <pxr/usd/usdGeom/xformOp.h>

#include <pxr/usd/sdf/copyUtils.h>
#include <pxr/base/work/loops.h>

#include <pxr/base/vt/array.h>
#include <pxr/base/vt/types.h>
#include <pxr/base/tf/staticData.h>
#include <pxr/base/tf/token.h>
#include <pxr/base/gf/vec3f.h>

#pragma pop_macro("Handle")

#include "stepAPI.h"

#include "StepUSD/StepUsdPipeline.h"
#include "StepUSD/OpenCascadeAssembly.h"
#include "StepUSD/Logger.h"
#include "StepUSD/UsdUtils.h"

PXR_NAMESPACE_USING_DIRECTIVE

// Write CAD pat
void StepUsdPipeline::writePartClass(
    UsdStageRefPtr prototypesStage,
    const UsdPrim& prototypesPrimOnContainerStage,
    const SdfPath& partPath
) {
    std::optional<SdfReference> defaultParamsRef = StepUsdPipeline::getPrototypesDefaultParams(prototypesPrimOnContainerStage);

    fs::path containerStagePath = fs::canonical(
        prototypesPrimOnContainerStage.GetStage()->GetRootLayer()->GetResolvedPath().GetPathString()
    );
    fs::path prototypesStagePath = fs::canonical(
        prototypesStage->GetRootLayer()->GetResolvedPath().GetPathString()
    );

    fs::path relativePath = fs::relative(containerStagePath, prototypesStagePath.parent_path());

    SdfPath realPartClassPath = this->pathConfig.containerPrimPath.AppendChild(partPath.GetNameToken());
    UsdPrim partPrim = prototypesStage->CreateClassPrim(realPartClassPath);

    prototypesStage->GetPrimAtPath(this->pathConfig.containerPrimPath).SetSpecifier(SdfSpecifierOver);

    UsdGeomImageable(partPrim).CreateVisibilityAttr().Set(UsdGeomTokens->inherited);

    auto makeClassChild = [&](const char* name) {
        SdfPath childPath = realPartClassPath.AppendChild(TfToken(name));
        UsdPrim child = prototypesStage->OverridePrim(childPath);
        UsdGeomImageable(child).CreateVisibilityAttr().Set(UsdGeomTokens->inherited);
    };

    makeClassChild("Mesh");
    makeClassChild("Wireframe");
    makeClassChild("Sketch");
    makeClassChild("SketchPlanes");
    
    if (defaultParamsRef.has_value()) {
        partPrim.GetPrim().GetReferences().AddReference(
            relativePath.string(),
            defaultParamsRef->GetPrimPath(),
            defaultParamsRef->GetLayerOffset()
        );
    }
}

// MARK: - Write Prototype Xforms
void StepUsdPipeline::writePrototypeXforms(
    PrototypeContainer& proto,
    LabelMap<SdfPath>& prototypePaths
) {
    const auto& defs = proto.model->getDefinitionShapes();
    
    const int total = (int)defs.size();
    int completed = 0;

    std::string logLabel = "";
    if (!proto.variantSetName.empty()) {
        logLabel = " {" + proto.variantSetName + "=" + proto.variantName + "}";
    }

    std::optional<SdfReference> defaultParamsRef;
    fs::path relativePath;

    UsdGeomXform::Define(proto.stage, this->pathConfig.containerPrimPath);
    
    SdfPath partPath = this->pathConfig.containerPrimPath.AppendChild(TfToken("Part"));
    const LabelMap<std::string>& definitionNames = proto.model->definitionNames;

    for (int defIdx = 0; defIdx < total; defIdx++) {
        const TDF_Label& defLabel = defs[defIdx].first;

        // Guard against already-processed label — use defLabel, not iterator
        if (prototypePaths.count(defLabel)) {
            completed++;
            continue;
        }

        auto it = definitionNames.find(defLabel);
        std::string rawName;
        bool hasRealName = (it != definitionNames.end()
                            && !it->second.empty()
                            && !isAutoGeneratedName(it->second));

        std::string suffix = stableLabelSuffix(defLabel);

        if (hasRealName) {
            rawName = sanitizeUsdName(it->second) + "__" + suffix;
        } else {
            rawName = "__" + suffix;
        }

        SdfPath protoPath = this->pathConfig.prototypesPath.AppendChild(TfToken(rawName));

        if (!proto.makeFreshStage && proto.stage->GetPrimAtPath(protoPath).IsValid()) {
            prototypePaths[defLabel] = protoPath;
            continue;
        }

        UsdPrim protoPrim = proto.stage->DefinePrim(protoPath);
        if (!protoPrim.IsValid()) {
            std::cerr << "writePrototypeXform: prim invalid after Define at " << protoPath << "\n";
            continue;
        }
        prototypePaths[defLabel] = protoPath;

        if (!proto.makeFreshStage && protoPrim.IsValid()) {
            completed++;
            if (Logger::activeLevel == Logger::DEBUG) {
                //LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Skip existing prototype: " + protoPath.GetString());
            } else {
                LOG_PROGRESS(completed, total, "Writing prototypes " + logLabel);
            }
            continue;
        }

        TCollection_AsciiString entry;
        TDF_Tool::Entry(defLabel, entry);
        
        AutolibStepAPI api(protoPrim);
        UsdGeomPrimvar labelPrimvar(api.CreateStepLabelAttr());
        
        {
            SdfChangeBlock changeBlock;
            
            std::string displayName = hasRealName ? it->second : ("Part_" + suffix);
            protoPrim.SetDisplayName(displayName);
            protoPrim.GetInherits().AddInherit(partPath);
            
            labelPrimvar.SetInterpolation(UsdGeomTokens->constant);
            labelPrimvar.Set(TfToken(entry.ToCString()));
        }

        completed++;
        if (Logger::activeLevel == Logger::DEBUG) {
            LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Writing prototype: " + protoPath.GetString());
        } else {
            LOG_PROGRESS(completed, total, "Writing prototypes " + logLabel);
        }
    }
    LOG_PROGRESS_DONE();
}

// MARK: - Prototype Geometry

// rotation block: transposed relative to OCC Value(row,col) convention
// translation: from TranslationPart() into the last row
static GfMatrix4d trsfToGfMatrix(const gp_Trsf& t, double linearScale) {
    gp_XYZ trans = t.TranslationPart();
    auto clean = [](double v) { return std::abs(v) < 1e-10 ? 0.0 : v; };
    return GfMatrix4d(
        clean(t.Value(1,1)), clean(t.Value(2,1)), clean(t.Value(3,1)), 0.0,
        clean(t.Value(1,2)), clean(t.Value(2,2)), clean(t.Value(3,2)), 0.0,
        clean(t.Value(1,3)), clean(t.Value(2,3)), clean(t.Value(3,3)), 0.0,
        clean(trans.X() * linearScale),
        clean(trans.Y() * linearScale),
        clean(trans.Z() * linearScale),
        1.0
    );
}

// Assembly Xforms
void StepUsdPipeline::writeAssemblyXforms(
    const PrototypeContainer& proto, 
    const std::vector<SdfPath>& paths
) {

    const auto& partNodes = proto.model->partNodes;
    const double& linearScale = proto.sourceToOutputScale;
    LOG_SCOPED_TIMER("writeAssemblyXforms (" + std::to_string(partNodes.size()) + " nodes)");
    
    // pre compute which instances have children
    std::vector<bool> hasChildren(partNodes.size(), false);
    for (size_t i = 0; i < partNodes.size(); i++) {
        if (partNodes[i].parentIdx != -1)
            hasChildren[partNodes[i].parentIdx] = true;
    }
    // Define all xform nodes, wire references, and author transforms
    const int total = (int)partNodes.size();
    int completed = 0;
    for (size_t i = 0; i < partNodes.size(); i++) {
        const OpenCascadeAssembly::PartNode& node = partNodes[i];
        UsdGeomXform xform = UsdGeomXform::Define(proto.stage, paths[i]);
        if (!xform) {
            std::cerr << "[" << i << "] Failed to define Xform at " << paths[i] << "\n";
            completed++;
            if (Logger::activeLevel == Logger::DEBUG) {
                LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Failed to write Assembly Xform for " + paths[i].GetString());
            } else {
                LOG_PROGRESS(completed, total, "Writing Assembly");
            }
            continue;
        }
        {
            SdfChangeBlock changeBlock;

            TCollection_AsciiString entry;
            TDF_Tool::Entry(node.instanceLabel, entry);
            
            AutolibStepAPI api(xform.GetPrim());
            api.CreateStepLabelAttr().Set(TfToken(entry.ToCString()));

            if (!node.name.empty() && !isAutoGeneratedName(node.name)) {
                xform.GetPrim().SetDisplayName(node.name);
            } else {
                // no real name — display the hash portion only, without the leading __
                std::string pathName = paths[i].GetName();
                if (pathName.size() > 2 && pathName[0] == '_' && pathName[1] == '_') {
                    xform.GetPrim().SetDisplayName(pathName.substr(2));
                }
            }
            
            // Usd composes the full world transform later
            xform.AddTransformOp().Set(trsfToGfMatrix(node.localTransform, linearScale));
            if (node.type == OpenCascadeAssembly::PartNodeType::Leaf) {
                auto protoIter = proto.model->prototypePaths.find(node.definitionLabel);
                if (protoIter == proto.model->prototypePaths.end()) {
                    completed++;
                    if (Logger::activeLevel == Logger::DEBUG) {
                        LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Skip missing prototype Assembly Xform: " + paths[i].GetString());
                    } else {
                        LOG_PROGRESS(completed, total, "Writing Assembly");
                    }
                    continue;
                }

                const SdfPath& assemblyProtoPath = protoIter->second;

                xform.GetPrim().GetReferences().AddInternalReference(assemblyProtoPath);
                UsdModelAPI(xform.GetPrim()).SetKind(TfToken("component"));
                if (!hasChildren[i]) {
                    xform.GetPrim().SetInstanceable(true);
                }
                UsdGeomImageable api(xform.GetPrim());
                api.GetVisibilityAttr().Set(UsdGeomTokens->inherited);
                if (node.color.has_value()) { // TODO: Support muliple colors per mesh
                    VtArray<GfVec3f> displayColor = {{
                        static_cast<float>(node.color->Red()),
                        static_cast<float>(node.color->Green()),
                        static_cast<float>(node.color->Blue())
                    }};
                    UsdAttribute colorAttr = xform.GetPrim().CreateAttribute(
                        TfToken("primvars:displayColor"),
                        SdfValueTypeNames->Color3fArray,
                        false
                    );
                    colorAttr.Set(displayColor);
                    UsdGeomPrimvar labelPrimvar(colorAttr);
                    labelPrimvar.SetInterpolation(UsdGeomTokens->constant);
                }
                if (!node.visible) {
                    UsdGeomImageable(xform.GetPrim())
                        .CreateVisibilityAttr()
                        .Set(UsdGeomTokens->invisible);
                }
            } else {
                UsdModelAPI(xform.GetPrim()).SetKind(TfToken("assembly"));
            }
        } // SdfChangeBlock
        completed++;
        if (Logger::activeLevel == Logger::DEBUG) {
            LOG_DEBUG("[" + std::to_string(completed) + "/" + std::to_string(total) + "] Writing Assembly: " + paths[i].GetString());
        } else {
            LOG_PROGRESS(completed, total, "Writing Assembly");
        }
    }
    LOG_PROGRESS_DONE();
}

void StepUsdPipeline::writePrototypeGeometries(
    UsdStageRefPtr stage,
    const std::vector<ProtoGeomJob>& inJobs,
    const std::unordered_set<SdfPath, SdfPath::Hash>& selectedPaths,
    const std::string& variantSetName,
    const std::string& variantName
) {
    const int total = (int)inJobs.size();
    if (total == 0) return;

    // Create a mutable copy of the jobs vector 
    // so we can sort it for load balancing
    std::vector<ProtoGeomJob> jobs = inJobs;
    std::sort(jobs.begin(), jobs.end(), [](const ProtoGeomJob& a, const ProtoGeomJob& b) {
        // Sort descending by number of points to process larger geometries first
        return a.routine.size() > b.routine.size();
    });

    std::atomic<int> completed(0);
    std::string logLabel = "";
    if (!variantSetName.empty()) {
        logLabel = " {" + variantSetName + "=" + variantName + "}";
    }

    struct ThreadResult {
        int startIdx;
        int endIdx;
        SdfLayerRefPtr layer;
    };

    std::vector<ThreadResult> threadResults;
    std::mutex resultsMutex;

    // This MAY help resovle a data race
    // with creating use stages in the code below
    int grainSize = 4;
    
    WorkParallelForN(total, [&](int startIdx, int endIdx) {
        TfErrorMark mark;
        SdfLayerRefPtr threadLayer = SdfLayer::CreateAnonymous();
        UsdStageRefPtr threadStage = UsdStage::Open(threadLayer);

        // their properties are later populated in the SdfChangeBlock 
        for (int i = startIdx; i < endIdx; i++) {
            const SdfPath& protoPath = jobs[i].protoPath;
            const TessParams& params = jobs[i].params;
            const TessellationRoutine& routine = jobs[i].routine;

            if (!selectedPaths.empty() && !isPrototypeActiveInFilter(selectedPaths, protoPath, variantSetName, variantName)) {
                continue;
            }

            UsdGeomScope protoXform;
                
            auto variantSelection = protoPath.GetVariantSelection();
            
            if (!variantSelection.first.empty()) {
                SdfPath baseProtoPath = protoPath.StripAllVariantSelections();
                
                UsdPrim basePrim = threadStage->GetPrimAtPath(baseProtoPath);
                if (!basePrim) {
                    protoXform = UsdGeomScope::Define(threadStage, baseProtoPath);
                    basePrim = protoXform.GetPrim();
                } else {
                    protoXform = UsdGeomScope(basePrim);
                }
                
                UsdVariantSet vset = basePrim.GetVariantSets().AddVariantSet(variantSelection.first);
                vset.AddVariant(variantSelection.second);
                vset.SetVariantSelection(variantSelection.second);
                UsdEditContext ctx(vset.GetVariantEditContext());
                
                routine.clearPrim(threadStage, baseProtoPath);
                routine.definePrim(threadStage, baseProtoPath, params);

            } else {
                protoXform = UsdGeomScope::Get(threadStage, protoPath);
                if (!protoXform) {
                    protoXform = UsdGeomScope::Define(threadStage, protoPath);
                }

                if (!protoXform) {
                    LOG_ERR("Failed to define scope at " + protoPath.GetString());
                    continue;
                }
                        
                routine.clearPrim(threadStage, protoPath);
                routine.definePrim(threadStage, protoPath, params);
            }
        }

        if (!mark.IsClean()) {
            for (const auto& error : mark)
                LOG_ERR("Usd: " + error.GetCommentary());
        }

        { // SdfChangeBlock
            SdfChangeBlock block;
            for (int i = startIdx; i < endIdx; i++) {
                const SdfPath& protoPath = jobs[i].protoPath;
                const TessParams& params = jobs[i].params;
                const TessellationRoutine& routine = jobs[i].routine;

                if (!selectedPaths.empty() && !isPrototypeActiveInFilter(selectedPaths, protoPath, variantSetName, variantName)) {
                    int c = ++completed;
                    if (Logger::activeLevel != Logger::DEBUG) {
                        LOG_PROGRESS(c, total, "Writing geometry" + logLabel);
                    }
                    continue;
                }

                auto variantSelection = protoPath.GetVariantSelection();
                SdfPath writeProtoPath = variantSelection.first.empty() ? protoPath : protoPath.StripAllVariantSelections();
                
                // If variant selected, we need the edit context 
                // active to author values inside the variant
                std::optional<UsdEditContext> ctx;
                if (!variantSelection.first.empty()) {
                    UsdPrim basePrim = threadStage->GetPrimAtPath(writeProtoPath);
                    UsdVariantSet vset = basePrim.GetVariantSets().AddVariantSet(variantSelection.first);
                    vset.AddVariant(variantSelection.second);
                    vset.SetVariantSelection(variantSelection.second);
                    ctx.emplace(vset.GetVariantEditContext());
                }

                UsdGeomScope protoXform = UsdGeomScope::Get(threadStage, writeProtoPath);

                if (!protoXform) {
                    LOG_ERR("writePrototypeGeometries: protoXform invalid at " + writeProtoPath.GetString() + " — define pass was skipped or failed");
                    int c = ++completed;
                    LOG_PROGRESS(c, total, "Writing geometry" + logLabel);
                    continue;
                }

                routine.writePrim(threadStage, writeProtoPath, params);

                int c = ++completed;
                if (Logger::activeLevel == Logger::DEBUG) {
                    LOG_DEBUG("[" + std::to_string(c) + "/" + std::to_string(total) + "] Writing geometry: " + protoPath.GetString());
                } else {
                    LOG_PROGRESS(c, total, "Writing geometry" + logLabel);
                }
            }
        } // SdfChangeBlock
        
        if (!mark.IsClean()) {
            for (const auto& error : mark)
                LOG_ERR("Usd: " + error.GetCommentary());
        }

        std::lock_guard<std::mutex> resLock(resultsMutex);
        threadResults.push_back({startIdx, endIdx, threadLayer});
    }, grainSize);

    // Merge back on the main stage

    // There are two passes here to handle variant and non-variant geometry separately 
    // SdfCopy doesn't handle copying into variant bodies, so geometry under variants 
    // is written directly to the main stage in a separate pass

    { // SdfChangeBlock
        SdfChangeBlock changeBlock;
        SdfLayerHandle mainLayer = stage->GetRootLayer();

        // pre-create variant specs in mainLayer so the variant bodies exist
        for (const auto& res : threadResults) {
            if (!res.layer) continue;
            for (size_t i = res.startIdx; i < res.endIdx; i++) {
                const SdfPath& protoPath = jobs[i].protoPath;
                auto variantSelection = protoPath.GetVariantSelection();
                if (variantSelection.first.empty()) continue; // skip variants 

                SdfPath baseProtoPath = protoPath.StripAllVariantSelections();
                SdfPrimSpecHandle primSpec = mainLayer->GetPrimAtPath(baseProtoPath);
                if (!primSpec) continue;

                SdfVariantSetSpecHandle vsetSpec;
                auto vsetProxy = primSpec->GetVariantSets();
                auto vsetIt = vsetProxy.find(variantSelection.first);
                if (vsetIt == vsetProxy.end()) {
                    vsetSpec = SdfVariantSetSpec::New(primSpec, variantSelection.first);
                    primSpec->GetVariantSetNameList().Prepend(variantSelection.first);
                } else {
                    vsetSpec = vsetIt->second;
                }

                auto variantProxy = vsetSpec->GetVariants();
                if (variantProxy.find(variantSelection.second) == variantProxy.end()) {
                    SdfVariantSpec::New(vsetSpec, variantSelection.second);
                }
            }
        }

        // write the non variants
        for (const auto& res : threadResults) {
            if (!res.layer) continue;
            for (size_t i = res.startIdx; i < res.endIdx; i++) {
                const SdfPath& protoPath = jobs[i].protoPath;
                if (!selectedPaths.empty() && !isPrototypeActiveInFilter(selectedPaths, protoPath, variantSetName, variantName)) {
                    continue; // Skip filtered
                }
                if (!protoPath.GetVariantSelection().first.empty()) continue; // only non variants

                SdfPath copyPath = protoPath.GetVariantSelection().first.empty() ? protoPath : protoPath.StripAllVariantSelections();
                
                SdfPrimSpecHandle srcSpec = res.layer->GetPrimAtPath(copyPath);
                SdfPrimSpecHandle dstSpec = mainLayer->GetPrimAtPath(copyPath);
                if (srcSpec && dstSpec) {
                    dstSpec->SetTypeName(srcSpec->GetTypeName());
                    for (const auto& prop : srcSpec->GetProperties()) {
                        SdfCopySpec(res.layer, prop->GetPath(), mainLayer, prop->GetPath());
                    }
                    for (const auto& child : srcSpec->GetNameChildren()) {
                        SdfCopySpec(res.layer, child->GetPath(), mainLayer, child->GetPath());
                    }
                } else {
                    SdfCopySpec(res.layer, copyPath, mainLayer, copyPath);
                }
            }
        }
    } // SdfChangeBlock

    // Variant geometry written to main stage
    for (const auto& res : threadResults) {
        if (!res.layer) continue;
        for (size_t i = res.startIdx; i < res.endIdx; i++) {
            const SdfPath& protoPath = jobs[i].protoPath;
            if (!selectedPaths.empty() &&
                !isPrototypeActiveInFilter(selectedPaths, protoPath, variantSetName, variantName)) {
                continue;
            }

            auto variantSelection = protoPath.GetVariantSelection();
            if (variantSelection.first.empty()) continue;

            const TessParams& params = jobs[i].params;
            const TessellationRoutine& routine = jobs[i].routine;

            SdfPath baseProtoPath = protoPath.StripAllVariantSelections();

            UsdPrim basePrim = stage->GetPrimAtPath(baseProtoPath);
            if (!basePrim) {
                LOG_ERR("Missing base prim at " + baseProtoPath.GetString() + "\n");
                continue;
            }

            // t
            bool hasAuthoredActive = basePrim.GetPrim().HasAuthoredActive();
            bool initialActive = true;
            if (hasAuthoredActive) {
                initialActive = basePrim.GetPrim().IsActive();
                basePrim.GetPrim().SetActive(true);
            }

            UsdVariantSet vset = basePrim.GetVariantSets().AddVariantSet(variantSelection.first);
            vset.AddVariant(variantSelection.second);
            vset.SetVariantSelection(variantSelection.second);
            UsdEditContext ctx(vset.GetVariantEditContext());

            // Clear any previously written geometry under this variant
            routine.clearPrim(stage, baseProtoPath);
            routine.definePrim(stage, baseProtoPath, params);

            {
                SdfChangeBlock changeBlock;
                routine.writePrim(stage, baseProtoPath, params);
            }

            if (hasAuthoredActive) {
                basePrim.GetPrim().SetActive(initialActive);
            } else {
                basePrim.GetPrim().ClearActive();
            }
        }
    }

    LOG_PROGRESS_DONE();
}